services:
  - type: web
    name: backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://tiktok_platform:password123@cluster0.mongodb.net/tiktok-platform?retryWrites=true&w=majority
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
  
  - type: web
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
